package com.loiane.tratamentoDeErroExcecoes;

public class Finally_Antes {
    public static void main(String[] args) {
        int[] numeros = {10, 2, 0, 1, 3, 0};
        int[] n = {2, 1, 0, 4};

        for (int index = 0; index < numeros.length; index++) {
            try {
                System.out.println("A divis達o de " + numeros[index] + " por " + n[index] + ", e igual: " + numeros[index] / n[index]);
            } catch (ArithmeticException e) {
                System.out.println("N達o se pode fazer divis達o com zero");
                System.exit(0);
            } catch (ArrayIndexOutOfBoundsException e) {
                System.out.println("N達o pode acessar indice fora do tamanho do array");
                System.exit(0);
            } finally {
                System.out.println("Fim do bloco try ou catch");
            }
        }
    }
}
